# Generated by Django 4.0.1 on 2022-01-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription2', models.TextField(verbose_name='Навыки')),
                ('sent_at2', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='discription',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='link',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
